//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanVien_Ent", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class NhanVien_Ent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaLamViecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChucVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_nhanvienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaLamViec {
            get {
                return this.CaLamViecField;
            }
            set {
                if ((object.ReferenceEquals(this.CaLamViecField, value) != true)) {
                    this.CaLamViecField = value;
                    this.RaisePropertyChanged("CaLamViec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChucVu {
            get {
                return this.ChucVuField;
            }
            set {
                if ((object.ReferenceEquals(this.ChucVuField, value) != true)) {
                    this.ChucVuField = value;
                    this.RaisePropertyChanged("ChucVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ho {
            get {
                return this.HoField;
            }
            set {
                if ((object.ReferenceEquals(this.HoField, value) != true)) {
                    this.HoField = value;
                    this.RaisePropertyChanged("Ho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_nhanvien {
            get {
                return this.Id_nhanvienField;
            }
            set {
                if ((this.Id_nhanvienField.Equals(value) != true)) {
                    this.Id_nhanvienField = value;
                    this.RaisePropertyChanged("Id_nhanvien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NhanVien_Wcf.INhanVien_WCF")]
    public interface INhanVien_WCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetNhanVien_by_ID", ReplyAction="http://tempuri.org/INhanVien_WCF/GetNhanVien_by_IDResponse")]
        QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent GetNhanVien_by_ID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetNhanVien_by_ID", ReplyAction="http://tempuri.org/INhanVien_WCF/GetNhanVien_by_IDResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent> GetNhanVien_by_IDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetChucVu", ReplyAction="http://tempuri.org/INhanVien_WCF/GetChucVuResponse")]
        int GetChucVu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetChucVu", ReplyAction="http://tempuri.org/INhanVien_WCF/GetChucVuResponse")]
        System.Threading.Tasks.Task<int> GetChucVuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetHoTen_NhanVien", ReplyAction="http://tempuri.org/INhanVien_WCF/GetHoTen_NhanVienResponse")]
        string GetHoTen_NhanVien(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetHoTen_NhanVien", ReplyAction="http://tempuri.org/INhanVien_WCF/GetHoTen_NhanVienResponse")]
        System.Threading.Tasks.Task<string> GetHoTen_NhanVienAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetID_by_Email", ReplyAction="http://tempuri.org/INhanVien_WCF/GetID_by_EmailResponse")]
        int GetID_by_Email(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetID_by_Email", ReplyAction="http://tempuri.org/INhanVien_WCF/GetID_by_EmailResponse")]
        System.Threading.Tasks.Task<int> GetID_by_EmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetEmail_by_ID", ReplyAction="http://tempuri.org/INhanVien_WCF/GetEmail_by_IDResponse")]
        string GetEmail_by_ID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetEmail_by_ID", ReplyAction="http://tempuri.org/INhanVien_WCF/GetEmail_by_IDResponse")]
        System.Threading.Tasks.Task<string> GetEmail_by_IDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetNhanViens", ReplyAction="http://tempuri.org/INhanVien_WCF/GetNhanViensResponse")]
        QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] GetNhanViens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/GetNhanViens", ReplyAction="http://tempuri.org/INhanVien_WCF/GetNhanViensResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> GetNhanViensAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/SapXepChucVu", ReplyAction="http://tempuri.org/INhanVien_WCF/SapXepChucVuResponse")]
        QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] SapXepChucVu(int chucvu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/SapXepChucVu", ReplyAction="http://tempuri.org/INhanVien_WCF/SapXepChucVuResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> SapXepChucVuAsync(int chucvu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/SapXepCaLamViec", ReplyAction="http://tempuri.org/INhanVien_WCF/SapXepCaLamViecResponse")]
        QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] SapXepCaLamViec(int caLamViec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/SapXepCaLamViec", ReplyAction="http://tempuri.org/INhanVien_WCF/SapXepCaLamViecResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> SapXepCaLamViecAsync(int caLamViec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/DangNhapHeThong", ReplyAction="http://tempuri.org/INhanVien_WCF/DangNhapHeThongResponse")]
        bool DangNhapHeThong(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/DangNhapHeThong", ReplyAction="http://tempuri.org/INhanVien_WCF/DangNhapHeThongResponse")]
        System.Threading.Tasks.Task<bool> DangNhapHeThongAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/ThemNhanVien", ReplyAction="http://tempuri.org/INhanVien_WCF/ThemNhanVienResponse")]
        bool ThemNhanVien(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/ThemNhanVien", ReplyAction="http://tempuri.org/INhanVien_WCF/ThemNhanVienResponse")]
        System.Threading.Tasks.Task<bool> ThemNhanVienAsync(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/CapNhatNhanVien", ReplyAction="http://tempuri.org/INhanVien_WCF/CapNhatNhanVienResponse")]
        bool CapNhatNhanVien(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/CapNhatNhanVien", ReplyAction="http://tempuri.org/INhanVien_WCF/CapNhatNhanVienResponse")]
        System.Threading.Tasks.Task<bool> CapNhatNhanVienAsync(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/CapNhatMatKhau", ReplyAction="http://tempuri.org/INhanVien_WCF/CapNhatMatKhauResponse")]
        bool CapNhatMatKhau(string email, string matKhaucu, string matkhaumoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/CapNhatMatKhau", ReplyAction="http://tempuri.org/INhanVien_WCF/CapNhatMatKhauResponse")]
        System.Threading.Tasks.Task<bool> CapNhatMatKhauAsync(string email, string matKhaucu, string matkhaumoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/XoaNhanVien_by_Email", ReplyAction="http://tempuri.org/INhanVien_WCF/XoaNhanVien_by_EmailResponse")]
        bool XoaNhanVien_by_Email(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/XoaNhanVien_by_Email", ReplyAction="http://tempuri.org/INhanVien_WCF/XoaNhanVien_by_EmailResponse")]
        System.Threading.Tasks.Task<bool> XoaNhanVien_by_EmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/TimKiem_NhanVien_by_HoTen", ReplyAction="http://tempuri.org/INhanVien_WCF/TimKiem_NhanVien_by_HoTenResponse")]
        QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] TimKiem_NhanVien_by_HoTen(string ho, string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVien_WCF/TimKiem_NhanVien_by_HoTen", ReplyAction="http://tempuri.org/INhanVien_WCF/TimKiem_NhanVien_by_HoTenResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> TimKiem_NhanVien_by_HoTenAsync(string ho, string ten);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INhanVien_WCFChannel : QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.INhanVien_WCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NhanVien_WCFClient : System.ServiceModel.ClientBase<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.INhanVien_WCF>, QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.INhanVien_WCF {
        
        public NhanVien_WCFClient() {
        }
        
        public NhanVien_WCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NhanVien_WCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanVien_WCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanVien_WCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent GetNhanVien_by_ID(int id) {
            return base.Channel.GetNhanVien_by_ID(id);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent> GetNhanVien_by_IDAsync(int id) {
            return base.Channel.GetNhanVien_by_IDAsync(id);
        }
        
        public int GetChucVu(int id) {
            return base.Channel.GetChucVu(id);
        }
        
        public System.Threading.Tasks.Task<int> GetChucVuAsync(int id) {
            return base.Channel.GetChucVuAsync(id);
        }
        
        public string GetHoTen_NhanVien(int id) {
            return base.Channel.GetHoTen_NhanVien(id);
        }
        
        public System.Threading.Tasks.Task<string> GetHoTen_NhanVienAsync(int id) {
            return base.Channel.GetHoTen_NhanVienAsync(id);
        }
        
        public int GetID_by_Email(string email) {
            return base.Channel.GetID_by_Email(email);
        }
        
        public System.Threading.Tasks.Task<int> GetID_by_EmailAsync(string email) {
            return base.Channel.GetID_by_EmailAsync(email);
        }
        
        public string GetEmail_by_ID(int id) {
            return base.Channel.GetEmail_by_ID(id);
        }
        
        public System.Threading.Tasks.Task<string> GetEmail_by_IDAsync(int id) {
            return base.Channel.GetEmail_by_IDAsync(id);
        }
        
        public QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] GetNhanViens() {
            return base.Channel.GetNhanViens();
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> GetNhanViensAsync() {
            return base.Channel.GetNhanViensAsync();
        }
        
        public QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] SapXepChucVu(int chucvu) {
            return base.Channel.SapXepChucVu(chucvu);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> SapXepChucVuAsync(int chucvu) {
            return base.Channel.SapXepChucVuAsync(chucvu);
        }
        
        public QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] SapXepCaLamViec(int caLamViec) {
            return base.Channel.SapXepCaLamViec(caLamViec);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> SapXepCaLamViecAsync(int caLamViec) {
            return base.Channel.SapXepCaLamViecAsync(caLamViec);
        }
        
        public bool DangNhapHeThong(string email, string pass) {
            return base.Channel.DangNhapHeThong(email, pass);
        }
        
        public System.Threading.Tasks.Task<bool> DangNhapHeThongAsync(string email, string pass) {
            return base.Channel.DangNhapHeThongAsync(email, pass);
        }
        
        public bool ThemNhanVien(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent, string matKhau) {
            return base.Channel.ThemNhanVien(nv_ent, matKhau);
        }
        
        public System.Threading.Tasks.Task<bool> ThemNhanVienAsync(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent, string matKhau) {
            return base.Channel.ThemNhanVienAsync(nv_ent, matKhau);
        }
        
        public bool CapNhatNhanVien(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent) {
            return base.Channel.CapNhatNhanVien(nv_ent);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatNhanVienAsync(QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent nv_ent) {
            return base.Channel.CapNhatNhanVienAsync(nv_ent);
        }
        
        public bool CapNhatMatKhau(string email, string matKhaucu, string matkhaumoi) {
            return base.Channel.CapNhatMatKhau(email, matKhaucu, matkhaumoi);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatMatKhauAsync(string email, string matKhaucu, string matkhaumoi) {
            return base.Channel.CapNhatMatKhauAsync(email, matKhaucu, matkhaumoi);
        }
        
        public bool XoaNhanVien_by_Email(string email) {
            return base.Channel.XoaNhanVien_by_Email(email);
        }
        
        public System.Threading.Tasks.Task<bool> XoaNhanVien_by_EmailAsync(string email) {
            return base.Channel.XoaNhanVien_by_EmailAsync(email);
        }
        
        public QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[] TimKiem_NhanVien_by_HoTen(string ho, string ten) {
            return base.Channel.TimKiem_NhanVien_by_HoTen(ho, ten);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.NhanVien_Wcf.NhanVien_Ent[]> TimKiem_NhanVien_by_HoTenAsync(string ho, string ten) {
            return base.Channel.TimKiem_NhanVien_by_HoTenAsync(ho, ten);
        }
    }
}
