<?xml version="1.0" encoding="utf-8"?><Database Name="KhachSan_DB" Class="DB_KhachSanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GlenOrient;Initial Catalog=KhachSan_DB;Persist Security Info=True;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="KhachSan_DBConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTiet_Check_In" Member="ChiTiet_Check_Ins">
    <Type Name="ChiTiet_Check_In">
      <Column Name="id_ChiTietCheckIn" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_phong" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_nhan_vien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_dichvu" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
      <Association Name="ChiTiet_Check_In_PhieuCheck_In" Member="PhieuCheck_Ins" ThisKey="id_ChiTietCheckIn" OtherKey="id_ChiTietCheckIn" Type="PhieuCheck_In" />
      <Association Name="Phong_ChiTiet_Check_In" Member="Phong" ThisKey="id_phong" OtherKey="id_Phong" Type="Phong" IsForeignKey="true" />
      <Association Name="NhanVien_ChiTiet_Check_In" Member="NhanVien" ThisKey="id_nhan_vien" OtherKey="id_NhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="DichVu_ChiTiet_Check_In" Member="DichVu" ThisKey="id_dichvu" OtherKey="id_DichVu" Type="DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="id_Phong" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="so_Phong" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="so_luong_nguoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tinh_trang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ghi_chu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_loai_phong" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="Phong_ChiTiet_Check_In" Member="ChiTiet_Check_Ins" ThisKey="id_Phong" OtherKey="id_phong" Type="ChiTiet_Check_In" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="id_loai_phong" OtherKey="id_loai_phong" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuCheck_In" Member="PhieuCheck_Ins">
    <Type Name="PhieuCheck_In">
      <Column Name="id_phieu_checkin" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_khach" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="id_ChiTietCheckIn" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_check_in" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gio_check_in" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="giam_gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="ChiTiet_Check_In_PhieuCheck_In" Member="ChiTiet_Check_In" ThisKey="id_ChiTietCheckIn" OtherKey="id_ChiTietCheckIn" Type="ChiTiet_Check_In" IsForeignKey="true" />
      <Association Name="KhachHang_PhieuCheck_In" Member="KhachHang" ThisKey="id_khach" OtherKey="id_khach" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="id_NhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ho" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="gioi_tinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_sinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="chuc_vu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ca_lam_viec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="mat_khau" Type="System.String" DbType="NChar(60) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_ChiTiet_Check_In" Member="ChiTiet_Check_Ins" ThisKey="id_NhanVien" OtherKey="id_nhan_vien" Type="ChiTiet_Check_In" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="id_loai_phong" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_loai_phong" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="gia_loai_phong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ghi_chu" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="id_loai_phong" OtherKey="id_loai_phong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="id_khach" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ho" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="so_cmnd" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="gioi_tinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="so_dien_thoai" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="quoc_tich" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_PhieuCheck_In" Member="PhieuCheck_Ins" ThisKey="id_khach" OtherKey="id_khach" Type="PhieuCheck_In" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="id_DichVu" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_dich_vu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gia_dich_vu" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="id_loai_dich_vu" Type="System.String" DbType="NChar(6) NOT NULL" CanBeNull="false" />
      <Association Name="DichVu_ChiTiet_Check_In" Member="ChiTiet_Check_Ins" ThisKey="id_DichVu" OtherKey="id_dichvu" Type="ChiTiet_Check_In" />
      <Association Name="LoaiDichVu_DichVu" Member="LoaiDichVu" ThisKey="id_loai_dich_vu" OtherKey="id_LoaiDichVu" Type="LoaiDichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDichVu" Member="LoaiDichVus">
    <Type Name="LoaiDichVu">
      <Column Name="id_LoaiDichVu" Type="System.String" DbType="NChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ten_loai_dich_vu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiDichVu_DichVu" Member="DichVus" ThisKey="id_LoaiDichVu" OtherKey="id_loai_dich_vu" Type="DichVu" />
    </Type>
  </Table>
</Database>