//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHACHSAN_PHANTAN.DichVu_Wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DichVu_Ent", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class DichVu_Ent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DonGiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_DichVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_LoaiDichVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDichVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiDichVuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DonGia {
            get {
                return this.DonGiaField;
            }
            set {
                if ((this.DonGiaField.Equals(value) != true)) {
                    this.DonGiaField = value;
                    this.RaisePropertyChanged("DonGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_DichVu {
            get {
                return this.Id_DichVuField;
            }
            set {
                if ((this.Id_DichVuField.Equals(value) != true)) {
                    this.Id_DichVuField = value;
                    this.RaisePropertyChanged("Id_DichVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_LoaiDichVu {
            get {
                return this.Id_LoaiDichVuField;
            }
            set {
                if ((this.Id_LoaiDichVuField.Equals(value) != true)) {
                    this.Id_LoaiDichVuField = value;
                    this.RaisePropertyChanged("Id_LoaiDichVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDichVu {
            get {
                return this.TenDichVuField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDichVuField, value) != true)) {
                    this.TenDichVuField = value;
                    this.RaisePropertyChanged("TenDichVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoaiDichVu {
            get {
                return this.TenLoaiDichVuField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiDichVuField, value) != true)) {
                    this.TenLoaiDichVuField = value;
                    this.RaisePropertyChanged("TenLoaiDichVu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DichVu_Wcf.IDichVu_WCF")]
    public interface IDichVu_WCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetDichVus", ReplyAction="http://tempuri.org/IDichVu_WCF/GetDichVusResponse")]
        QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[] GetDichVus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetDichVus", ReplyAction="http://tempuri.org/IDichVu_WCF/GetDichVusResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[]> GetDichVusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetDichVu_byIdDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/GetDichVu_byIdDichVuResponse")]
        QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent GetDichVu_byIdDichVu(int idDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetDichVu_byIdDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/GetDichVu_byIdDichVuResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent> GetDichVu_byIdDichVuAsync(int idDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetTenLoaiDichVu_byIdLoaiDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/GetTenLoaiDichVu_byIdLoaiDichVuResponse")]
        string GetTenLoaiDichVu_byIdLoaiDichVu(int idLoaiDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetTenLoaiDichVu_byIdLoaiDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/GetTenLoaiDichVu_byIdLoaiDichVuResponse")]
        System.Threading.Tasks.Task<string> GetTenLoaiDichVu_byIdLoaiDichVuAsync(int idLoaiDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDLoaiDV", ReplyAction="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDLoaiDVResponse")]
        QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[] TimKiemDichVu_byIDLoaiDV(int IDLoaiDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDLoaiDV", ReplyAction="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDLoaiDVResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[]> TimKiemDichVu_byIDLoaiDVAsync(int IDLoaiDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/ThemDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/ThemDichVuResponse")]
        bool ThemDichVu(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/ThemDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/ThemDichVuResponse")]
        System.Threading.Tasks.Task<bool> ThemDichVuAsync(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/CapNhatDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/CapNhatDichVuResponse")]
        bool CapNhatDichVu(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/CapNhatDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/CapNhatDichVuResponse")]
        System.Threading.Tasks.Task<bool> CapNhatDichVuAsync(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/XoaDichVu_byIDDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/XoaDichVu_byIDDichVuResponse")]
        bool XoaDichVu_byIDDichVu(int idDichVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/XoaDichVu_byIDDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/XoaDichVu_byIDDichVuResponse")]
        System.Threading.Tasks.Task<bool> XoaDichVu_byIDDichVuAsync(int idDichVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetIDLoaiDV_byTenLoai", ReplyAction="http://tempuri.org/IDichVu_WCF/GetIDLoaiDV_byTenLoaiResponse")]
        int GetIDLoaiDV_byTenLoai(string TenLoaiDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetIDLoaiDV_byTenLoai", ReplyAction="http://tempuri.org/IDichVu_WCF/GetIDLoaiDV_byTenLoaiResponse")]
        System.Threading.Tasks.Task<int> GetIDLoaiDV_byTenLoaiAsync(string TenLoaiDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetIDDichVu_byTenDV", ReplyAction="http://tempuri.org/IDichVu_WCF/GetIDDichVu_byTenDVResponse")]
        int GetIDDichVu_byTenDV(string TenDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetIDDichVu_byTenDV", ReplyAction="http://tempuri.org/IDichVu_WCF/GetIDDichVu_byTenDVResponse")]
        System.Threading.Tasks.Task<int> GetIDDichVu_byTenDVAsync(string TenDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDDichVuResponse")]
        QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[] TimKiemDichVu_byIDDichVu(int IDDichVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/TimKiemDichVu_byIDDichVuResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[]> TimKiemDichVu_byIDDichVuAsync(int IDDichVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetTenDichVu_byIdDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/GetTenDichVu_byIdDichVuResponse")]
        string GetTenDichVu_byIdDichVu(int idDV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDichVu_WCF/GetTenDichVu_byIdDichVu", ReplyAction="http://tempuri.org/IDichVu_WCF/GetTenDichVu_byIdDichVuResponse")]
        System.Threading.Tasks.Task<string> GetTenDichVu_byIdDichVuAsync(int idDV);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDichVu_WCFChannel : QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.IDichVu_WCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DichVu_WCFClient : System.ServiceModel.ClientBase<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.IDichVu_WCF>, QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.IDichVu_WCF {
        
        public DichVu_WCFClient() {
        }
        
        public DichVu_WCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DichVu_WCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVu_WCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVu_WCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[] GetDichVus() {
            return base.Channel.GetDichVus();
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[]> GetDichVusAsync() {
            return base.Channel.GetDichVusAsync();
        }
        
        public QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent GetDichVu_byIdDichVu(int idDV) {
            return base.Channel.GetDichVu_byIdDichVu(idDV);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent> GetDichVu_byIdDichVuAsync(int idDV) {
            return base.Channel.GetDichVu_byIdDichVuAsync(idDV);
        }
        
        public string GetTenLoaiDichVu_byIdLoaiDichVu(int idLoaiDV) {
            return base.Channel.GetTenLoaiDichVu_byIdLoaiDichVu(idLoaiDV);
        }
        
        public System.Threading.Tasks.Task<string> GetTenLoaiDichVu_byIdLoaiDichVuAsync(int idLoaiDV) {
            return base.Channel.GetTenLoaiDichVu_byIdLoaiDichVuAsync(idLoaiDV);
        }
        
        public QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[] TimKiemDichVu_byIDLoaiDV(int IDLoaiDV) {
            return base.Channel.TimKiemDichVu_byIDLoaiDV(IDLoaiDV);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[]> TimKiemDichVu_byIDLoaiDVAsync(int IDLoaiDV) {
            return base.Channel.TimKiemDichVu_byIDLoaiDVAsync(IDLoaiDV);
        }
        
        public bool ThemDichVu(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent) {
            return base.Channel.ThemDichVu(dv_ent);
        }
        
        public System.Threading.Tasks.Task<bool> ThemDichVuAsync(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent) {
            return base.Channel.ThemDichVuAsync(dv_ent);
        }
        
        public bool CapNhatDichVu(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent) {
            return base.Channel.CapNhatDichVu(dv_ent);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatDichVuAsync(QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent dv_ent) {
            return base.Channel.CapNhatDichVuAsync(dv_ent);
        }
        
        public bool XoaDichVu_byIDDichVu(int idDichVu) {
            return base.Channel.XoaDichVu_byIDDichVu(idDichVu);
        }
        
        public System.Threading.Tasks.Task<bool> XoaDichVu_byIDDichVuAsync(int idDichVu) {
            return base.Channel.XoaDichVu_byIDDichVuAsync(idDichVu);
        }
        
        public int GetIDLoaiDV_byTenLoai(string TenLoaiDV) {
            return base.Channel.GetIDLoaiDV_byTenLoai(TenLoaiDV);
        }
        
        public System.Threading.Tasks.Task<int> GetIDLoaiDV_byTenLoaiAsync(string TenLoaiDV) {
            return base.Channel.GetIDLoaiDV_byTenLoaiAsync(TenLoaiDV);
        }
        
        public int GetIDDichVu_byTenDV(string TenDV) {
            return base.Channel.GetIDDichVu_byTenDV(TenDV);
        }
        
        public System.Threading.Tasks.Task<int> GetIDDichVu_byTenDVAsync(string TenDV) {
            return base.Channel.GetIDDichVu_byTenDVAsync(TenDV);
        }
        
        public QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[] TimKiemDichVu_byIDDichVu(int IDDichVu) {
            return base.Channel.TimKiemDichVu_byIDDichVu(IDDichVu);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.DichVu_Wcf.DichVu_Ent[]> TimKiemDichVu_byIDDichVuAsync(int IDDichVu) {
            return base.Channel.TimKiemDichVu_byIDDichVuAsync(IDDichVu);
        }
        
        public string GetTenDichVu_byIdDichVu(int idDV) {
            return base.Channel.GetTenDichVu_byIdDichVu(idDV);
        }
        
        public System.Threading.Tasks.Task<string> GetTenDichVu_byIdDichVuAsync(int idDV) {
            return base.Channel.GetTenDichVu_byIdDichVuAsync(idDV);
        }
    }
}
