//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaoCao_Ent", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class BaoCao_Ent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BaoCao_Wcf.IBaoCao_WCF")]
    public interface IBaoCao_WCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoCao_WCF/GetBaoCaos", ReplyAction="http://tempuri.org/IBaoCao_WCF/GetBaoCaosResponse")]
        QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf.BaoCao_Ent[] GetBaoCaos(System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaoCao_WCF/GetBaoCaos", ReplyAction="http://tempuri.org/IBaoCao_WCF/GetBaoCaosResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf.BaoCao_Ent[]> GetBaoCaosAsync(System.DateTime dt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaoCao_WCFChannel : QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf.IBaoCao_WCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaoCao_WCFClient : System.ServiceModel.ClientBase<QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf.IBaoCao_WCF>, QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf.IBaoCao_WCF {
        
        public BaoCao_WCFClient() {
        }
        
        public BaoCao_WCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaoCao_WCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaoCao_WCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaoCao_WCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf.BaoCao_Ent[] GetBaoCaos(System.DateTime dt) {
            return base.Channel.GetBaoCaos(dt);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.BaoCao_Wcf.BaoCao_Ent[]> GetBaoCaosAsync(System.DateTime dt) {
            return base.Channel.GetBaoCaosAsync(dt);
        }
    }
}
