//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuCheckIn_Ent", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class PhieuCheckIn_Ent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Giam_giaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan Gio_check_inField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan Gio_check_outField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_DichVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_NhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_PhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_khachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_phieu_checkinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Ngay_check_inField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Ngay_check_outField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongDichVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongKhachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrangThaiHoaDonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Giam_gia {
            get {
                return this.Giam_giaField;
            }
            set {
                if ((this.Giam_giaField.Equals(value) != true)) {
                    this.Giam_giaField = value;
                    this.RaisePropertyChanged("Giam_gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Gio_check_in {
            get {
                return this.Gio_check_inField;
            }
            set {
                if ((this.Gio_check_inField.Equals(value) != true)) {
                    this.Gio_check_inField = value;
                    this.RaisePropertyChanged("Gio_check_in");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Gio_check_out {
            get {
                return this.Gio_check_outField;
            }
            set {
                if ((this.Gio_check_outField.Equals(value) != true)) {
                    this.Gio_check_outField = value;
                    this.RaisePropertyChanged("Gio_check_out");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_DichVu {
            get {
                return this.Id_DichVuField;
            }
            set {
                if ((this.Id_DichVuField.Equals(value) != true)) {
                    this.Id_DichVuField = value;
                    this.RaisePropertyChanged("Id_DichVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_NhanVien {
            get {
                return this.Id_NhanVienField;
            }
            set {
                if ((this.Id_NhanVienField.Equals(value) != true)) {
                    this.Id_NhanVienField = value;
                    this.RaisePropertyChanged("Id_NhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Phong {
            get {
                return this.Id_PhongField;
            }
            set {
                if ((this.Id_PhongField.Equals(value) != true)) {
                    this.Id_PhongField = value;
                    this.RaisePropertyChanged("Id_Phong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_khach {
            get {
                return this.Id_khachField;
            }
            set {
                if ((this.Id_khachField.Equals(value) != true)) {
                    this.Id_khachField = value;
                    this.RaisePropertyChanged("Id_khach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_phieu_checkin {
            get {
                return this.Id_phieu_checkinField;
            }
            set {
                if ((this.Id_phieu_checkinField.Equals(value) != true)) {
                    this.Id_phieu_checkinField = value;
                    this.RaisePropertyChanged("Id_phieu_checkin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngay_check_in {
            get {
                return this.Ngay_check_inField;
            }
            set {
                if ((this.Ngay_check_inField.Equals(value) != true)) {
                    this.Ngay_check_inField = value;
                    this.RaisePropertyChanged("Ngay_check_in");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ngay_check_out {
            get {
                return this.Ngay_check_outField;
            }
            set {
                if ((this.Ngay_check_outField.Equals(value) != true)) {
                    this.Ngay_check_outField = value;
                    this.RaisePropertyChanged("Ngay_check_out");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuongDichVu {
            get {
                return this.SoLuongDichVuField;
            }
            set {
                if ((this.SoLuongDichVuField.Equals(value) != true)) {
                    this.SoLuongDichVuField = value;
                    this.RaisePropertyChanged("SoLuongDichVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuongKhach {
            get {
                return this.SoLuongKhachField;
            }
            set {
                if ((this.SoLuongKhachField.Equals(value) != true)) {
                    this.SoLuongKhachField = value;
                    this.RaisePropertyChanged("SoLuongKhach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrangThaiHoaDon {
            get {
                return this.TrangThaiHoaDonField;
            }
            set {
                if ((this.TrangThaiHoaDonField.Equals(value) != true)) {
                    this.TrangThaiHoaDonField = value;
                    this.RaisePropertyChanged("TrangThaiHoaDon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhieuCheckIn_Wcf.IPhieuCheckIn_WCF")]
    public interface IPhieuCheckIn_WCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckIn", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckInResponse")]
        bool ThemPhieuCheckIn(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckIn", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckInResponse")]
        System.Threading.Tasks.Task<bool> ThemPhieuCheckInAsync(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/lsPhieuCheckIn_ToDate", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/lsPhieuCheckIn_ToDateResponse")]
        QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] lsPhieuCheckIn_ToDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/lsPhieuCheckIn_ToDate", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/lsPhieuCheckIn_ToDateResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> lsPhieuCheckIn_ToDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckIns", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckInsResponse")]
        QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] GetPhieuCheckIns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckIns", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckInsResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> GetPhieuCheckInsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/GetKh_ChuaThanhToan_ByID", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/GetKh_ChuaThanhToan_ByIDResponse")]
        QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] GetKh_ChuaThanhToan_ByID(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/GetKh_ChuaThanhToan_ByID", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/GetKh_ChuaThanhToan_ByIDResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> GetKh_ChuaThanhToan_ByIDAsync(int idKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckIn_DichVu", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckIn_DichVuResponse")]
        bool ThemPhieuCheckIn_DichVu(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckIn_DichVu", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/ThemPhieuCheckIn_DichVuResponse")]
        System.Threading.Tasks.Task<bool> ThemPhieuCheckIn_DichVuAsync(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckIns_NoCheckOut", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckIns_NoCheckOutResponse")]
        QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] GetPhieuCheckIns_NoCheckOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckIns_NoCheckOut", ReplyAction="http://tempuri.org/IPhieuCheckIn_WCF/GetPhieuCheckIns_NoCheckOutResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> GetPhieuCheckIns_NoCheckOutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhieuCheckIn_WCFChannel : QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.IPhieuCheckIn_WCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhieuCheckIn_WCFClient : System.ServiceModel.ClientBase<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.IPhieuCheckIn_WCF>, QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.IPhieuCheckIn_WCF {
        
        public PhieuCheckIn_WCFClient() {
        }
        
        public PhieuCheckIn_WCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhieuCheckIn_WCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuCheckIn_WCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhieuCheckIn_WCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ThemPhieuCheckIn(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent) {
            return base.Channel.ThemPhieuCheckIn(phieucheckin_ent);
        }
        
        public System.Threading.Tasks.Task<bool> ThemPhieuCheckInAsync(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent) {
            return base.Channel.ThemPhieuCheckInAsync(phieucheckin_ent);
        }
        
        public QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] lsPhieuCheckIn_ToDate(System.DateTime date) {
            return base.Channel.lsPhieuCheckIn_ToDate(date);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> lsPhieuCheckIn_ToDateAsync(System.DateTime date) {
            return base.Channel.lsPhieuCheckIn_ToDateAsync(date);
        }
        
        public QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] GetPhieuCheckIns() {
            return base.Channel.GetPhieuCheckIns();
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> GetPhieuCheckInsAsync() {
            return base.Channel.GetPhieuCheckInsAsync();
        }
        
        public QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] GetKh_ChuaThanhToan_ByID(int idKH) {
            return base.Channel.GetKh_ChuaThanhToan_ByID(idKH);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> GetKh_ChuaThanhToan_ByIDAsync(int idKH) {
            return base.Channel.GetKh_ChuaThanhToan_ByIDAsync(idKH);
        }
        
        public bool ThemPhieuCheckIn_DichVu(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent) {
            return base.Channel.ThemPhieuCheckIn_DichVu(phieucheckin_ent);
        }
        
        public System.Threading.Tasks.Task<bool> ThemPhieuCheckIn_DichVuAsync(QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent phieucheckin_ent) {
            return base.Channel.ThemPhieuCheckIn_DichVuAsync(phieucheckin_ent);
        }
        
        public QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[] GetPhieuCheckIns_NoCheckOut() {
            return base.Channel.GetPhieuCheckIns_NoCheckOut();
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.PhieuCheckIn_Wcf.PhieuCheckIn_Ent[]> GetPhieuCheckIns_NoCheckOutAsync() {
            return base.Channel.GetPhieuCheckIns_NoCheckOutAsync();
        }
    }
}
