//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHACHSAN_PHANTAN.Phong_Wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phong_Ent", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class Phong_Ent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ghi_chuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_PhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_loai_phongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string So_PhongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int So_luong_nguoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tinh_trangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ghi_chu {
            get {
                return this.Ghi_chuField;
            }
            set {
                if ((object.ReferenceEquals(this.Ghi_chuField, value) != true)) {
                    this.Ghi_chuField = value;
                    this.RaisePropertyChanged("Ghi_chu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Phong {
            get {
                return this.Id_PhongField;
            }
            set {
                if ((this.Id_PhongField.Equals(value) != true)) {
                    this.Id_PhongField = value;
                    this.RaisePropertyChanged("Id_Phong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_loai_phong {
            get {
                return this.Id_loai_phongField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_loai_phongField, value) != true)) {
                    this.Id_loai_phongField = value;
                    this.RaisePropertyChanged("Id_loai_phong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string So_Phong {
            get {
                return this.So_PhongField;
            }
            set {
                if ((object.ReferenceEquals(this.So_PhongField, value) != true)) {
                    this.So_PhongField = value;
                    this.RaisePropertyChanged("So_Phong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int So_luong_nguoi {
            get {
                return this.So_luong_nguoiField;
            }
            set {
                if ((this.So_luong_nguoiField.Equals(value) != true)) {
                    this.So_luong_nguoiField = value;
                    this.RaisePropertyChanged("So_luong_nguoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tang {
            get {
                return this.TangField;
            }
            set {
                if ((this.TangField.Equals(value) != true)) {
                    this.TangField = value;
                    this.RaisePropertyChanged("Tang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tinh_trang {
            get {
                return this.Tinh_trangField;
            }
            set {
                if ((object.ReferenceEquals(this.Tinh_trangField, value) != true)) {
                    this.Tinh_trangField = value;
                    this.RaisePropertyChanged("Tinh_trang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Phong_Wcf.IPhong_WCF")]
    public interface IPhong_WCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetPhongs", ReplyAction="http://tempuri.org/IPhong_WCF/GetPhongsResponse")]
        QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] GetPhongs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetPhongs", ReplyAction="http://tempuri.org/IPhong_WCF/GetPhongsResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> GetPhongsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetIDPhong_by_SoPhong", ReplyAction="http://tempuri.org/IPhong_WCF/GetIDPhong_by_SoPhongResponse")]
        int GetIDPhong_by_SoPhong(string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetIDPhong_by_SoPhong", ReplyAction="http://tempuri.org/IPhong_WCF/GetIDPhong_by_SoPhongResponse")]
        System.Threading.Tasks.Task<int> GetIDPhong_by_SoPhongAsync(string sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/ThemPhong", ReplyAction="http://tempuri.org/IPhong_WCF/ThemPhongResponse")]
        bool ThemPhong(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/ThemPhong", ReplyAction="http://tempuri.org/IPhong_WCF/ThemPhongResponse")]
        System.Threading.Tasks.Task<bool> ThemPhongAsync(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/CapNhatPhong", ReplyAction="http://tempuri.org/IPhong_WCF/CapNhatPhongResponse")]
        bool CapNhatPhong(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/CapNhatPhong", ReplyAction="http://tempuri.org/IPhong_WCF/CapNhatPhongResponse")]
        System.Threading.Tasks.Task<bool> CapNhatPhongAsync(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/XoaPhong", ReplyAction="http://tempuri.org/IPhong_WCF/XoaPhongResponse")]
        bool XoaPhong(string id_Phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/XoaPhong", ReplyAction="http://tempuri.org/IPhong_WCF/XoaPhongResponse")]
        System.Threading.Tasks.Task<bool> XoaPhongAsync(string id_Phong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetPhong_by_ID", ReplyAction="http://tempuri.org/IPhong_WCF/GetPhong_by_IDResponse")]
        QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent GetPhong_by_ID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetPhong_by_ID", ReplyAction="http://tempuri.org/IPhong_WCF/GetPhong_by_IDResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent> GetPhong_by_IDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/SapXepTang", ReplyAction="http://tempuri.org/IPhong_WCF/SapXepTangResponse")]
        QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] SapXepTang(int Tang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/SapXepTang", ReplyAction="http://tempuri.org/IPhong_WCF/SapXepTangResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> SapXepTangAsync(int Tang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/SapXepTinhTrang", ReplyAction="http://tempuri.org/IPhong_WCF/SapXepTinhTrangResponse")]
        QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] SapXepTinhTrang(string TinhTrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/SapXepTinhTrang", ReplyAction="http://tempuri.org/IPhong_WCF/SapXepTinhTrangResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> SapXepTinhTrangAsync(string TinhTrang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/SapXepLoaiPhong", ReplyAction="http://tempuri.org/IPhong_WCF/SapXepLoaiPhongResponse")]
        QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] SapXepLoaiPhong(string idLoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/SapXepLoaiPhong", ReplyAction="http://tempuri.org/IPhong_WCF/SapXepLoaiPhongResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> SapXepLoaiPhongAsync(string idLoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/Tim_Kiem_By_SoPhong", ReplyAction="http://tempuri.org/IPhong_WCF/Tim_Kiem_By_SoPhongResponse")]
        QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] Tim_Kiem_By_SoPhong(string soPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/Tim_Kiem_By_SoPhong", ReplyAction="http://tempuri.org/IPhong_WCF/Tim_Kiem_By_SoPhongResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> Tim_Kiem_By_SoPhongAsync(string soPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetPhongTrong_byLoaiPhong", ReplyAction="http://tempuri.org/IPhong_WCF/GetPhongTrong_byLoaiPhongResponse")]
        QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] GetPhongTrong_byLoaiPhong(int idLoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetPhongTrong_byLoaiPhong", ReplyAction="http://tempuri.org/IPhong_WCF/GetPhongTrong_byLoaiPhongResponse")]
        System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> GetPhongTrong_byLoaiPhongAsync(int idLoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/DonGia", ReplyAction="http://tempuri.org/IPhong_WCF/DonGiaResponse")]
        decimal DonGia(string id_LoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/DonGia", ReplyAction="http://tempuri.org/IPhong_WCF/DonGiaResponse")]
        System.Threading.Tasks.Task<decimal> DonGiaAsync(string id_LoaiPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/getIDPhong", ReplyAction="http://tempuri.org/IPhong_WCF/getIDPhongResponse")]
        int getIDPhong(string soPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/getIDPhong", ReplyAction="http://tempuri.org/IPhong_WCF/getIDPhongResponse")]
        System.Threading.Tasks.Task<int> getIDPhongAsync(string soPhong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/getsoPhong_byID", ReplyAction="http://tempuri.org/IPhong_WCF/getsoPhong_byIDResponse")]
        string getsoPhong_byID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/getsoPhong_byID", ReplyAction="http://tempuri.org/IPhong_WCF/getsoPhong_byIDResponse")]
        System.Threading.Tasks.Task<string> getsoPhong_byIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/TinhTienPhong", ReplyAction="http://tempuri.org/IPhong_WCF/TinhTienPhongResponse")]
        double TinhTienPhong(int idLoaiPhong, int soNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/TinhTienPhong", ReplyAction="http://tempuri.org/IPhong_WCF/TinhTienPhongResponse")]
        System.Threading.Tasks.Task<double> TinhTienPhongAsync(int idLoaiPhong, int soNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/update_TinhTrangPhong", ReplyAction="http://tempuri.org/IPhong_WCF/update_TinhTrangPhongResponse")]
        bool update_TinhTrangPhong(int idPhong, int trangThai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/update_TinhTrangPhong", ReplyAction="http://tempuri.org/IPhong_WCF/update_TinhTrangPhongResponse")]
        System.Threading.Tasks.Task<bool> update_TinhTrangPhongAsync(int idPhong, int trangThai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetTenLoaiPhong_by_IDLoai", ReplyAction="http://tempuri.org/IPhong_WCF/GetTenLoaiPhong_by_IDLoaiResponse")]
        string GetTenLoaiPhong_by_IDLoai(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhong_WCF/GetTenLoaiPhong_by_IDLoai", ReplyAction="http://tempuri.org/IPhong_WCF/GetTenLoaiPhong_by_IDLoaiResponse")]
        System.Threading.Tasks.Task<string> GetTenLoaiPhong_by_IDLoaiAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhong_WCFChannel : QUANLYKHACHSAN_PHANTAN.Phong_Wcf.IPhong_WCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Phong_WCFClient : System.ServiceModel.ClientBase<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.IPhong_WCF>, QUANLYKHACHSAN_PHANTAN.Phong_Wcf.IPhong_WCF {
        
        public Phong_WCFClient() {
        }
        
        public Phong_WCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Phong_WCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Phong_WCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Phong_WCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] GetPhongs() {
            return base.Channel.GetPhongs();
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> GetPhongsAsync() {
            return base.Channel.GetPhongsAsync();
        }
        
        public int GetIDPhong_by_SoPhong(string sp) {
            return base.Channel.GetIDPhong_by_SoPhong(sp);
        }
        
        public System.Threading.Tasks.Task<int> GetIDPhong_by_SoPhongAsync(string sp) {
            return base.Channel.GetIDPhong_by_SoPhongAsync(sp);
        }
        
        public bool ThemPhong(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent) {
            return base.Channel.ThemPhong(phong_ent);
        }
        
        public System.Threading.Tasks.Task<bool> ThemPhongAsync(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent) {
            return base.Channel.ThemPhongAsync(phong_ent);
        }
        
        public bool CapNhatPhong(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent) {
            return base.Channel.CapNhatPhong(phong_ent);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatPhongAsync(QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent phong_ent) {
            return base.Channel.CapNhatPhongAsync(phong_ent);
        }
        
        public bool XoaPhong(string id_Phong) {
            return base.Channel.XoaPhong(id_Phong);
        }
        
        public System.Threading.Tasks.Task<bool> XoaPhongAsync(string id_Phong) {
            return base.Channel.XoaPhongAsync(id_Phong);
        }
        
        public QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent GetPhong_by_ID(string id) {
            return base.Channel.GetPhong_by_ID(id);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent> GetPhong_by_IDAsync(string id) {
            return base.Channel.GetPhong_by_IDAsync(id);
        }
        
        public QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] SapXepTang(int Tang) {
            return base.Channel.SapXepTang(Tang);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> SapXepTangAsync(int Tang) {
            return base.Channel.SapXepTangAsync(Tang);
        }
        
        public QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] SapXepTinhTrang(string TinhTrang) {
            return base.Channel.SapXepTinhTrang(TinhTrang);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> SapXepTinhTrangAsync(string TinhTrang) {
            return base.Channel.SapXepTinhTrangAsync(TinhTrang);
        }
        
        public QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] SapXepLoaiPhong(string idLoaiPhong) {
            return base.Channel.SapXepLoaiPhong(idLoaiPhong);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> SapXepLoaiPhongAsync(string idLoaiPhong) {
            return base.Channel.SapXepLoaiPhongAsync(idLoaiPhong);
        }
        
        public QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] Tim_Kiem_By_SoPhong(string soPhong) {
            return base.Channel.Tim_Kiem_By_SoPhong(soPhong);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> Tim_Kiem_By_SoPhongAsync(string soPhong) {
            return base.Channel.Tim_Kiem_By_SoPhongAsync(soPhong);
        }
        
        public QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[] GetPhongTrong_byLoaiPhong(int idLoaiPhong) {
            return base.Channel.GetPhongTrong_byLoaiPhong(idLoaiPhong);
        }
        
        public System.Threading.Tasks.Task<QUANLYKHACHSAN_PHANTAN.Phong_Wcf.Phong_Ent[]> GetPhongTrong_byLoaiPhongAsync(int idLoaiPhong) {
            return base.Channel.GetPhongTrong_byLoaiPhongAsync(idLoaiPhong);
        }
        
        public decimal DonGia(string id_LoaiPhong) {
            return base.Channel.DonGia(id_LoaiPhong);
        }
        
        public System.Threading.Tasks.Task<decimal> DonGiaAsync(string id_LoaiPhong) {
            return base.Channel.DonGiaAsync(id_LoaiPhong);
        }
        
        public int getIDPhong(string soPhong) {
            return base.Channel.getIDPhong(soPhong);
        }
        
        public System.Threading.Tasks.Task<int> getIDPhongAsync(string soPhong) {
            return base.Channel.getIDPhongAsync(soPhong);
        }
        
        public string getsoPhong_byID(int id) {
            return base.Channel.getsoPhong_byID(id);
        }
        
        public System.Threading.Tasks.Task<string> getsoPhong_byIDAsync(int id) {
            return base.Channel.getsoPhong_byIDAsync(id);
        }
        
        public double TinhTienPhong(int idLoaiPhong, int soNgay) {
            return base.Channel.TinhTienPhong(idLoaiPhong, soNgay);
        }
        
        public System.Threading.Tasks.Task<double> TinhTienPhongAsync(int idLoaiPhong, int soNgay) {
            return base.Channel.TinhTienPhongAsync(idLoaiPhong, soNgay);
        }
        
        public bool update_TinhTrangPhong(int idPhong, int trangThai) {
            return base.Channel.update_TinhTrangPhong(idPhong, trangThai);
        }
        
        public System.Threading.Tasks.Task<bool> update_TinhTrangPhongAsync(int idPhong, int trangThai) {
            return base.Channel.update_TinhTrangPhongAsync(idPhong, trangThai);
        }
        
        public string GetTenLoaiPhong_by_IDLoai(int id) {
            return base.Channel.GetTenLoaiPhong_by_IDLoai(id);
        }
        
        public System.Threading.Tasks.Task<string> GetTenLoaiPhong_by_IDLoaiAsync(int id) {
            return base.Channel.GetTenLoaiPhong_by_IDLoaiAsync(id);
        }
    }
}
